@extends('frontend.sitemap.template')

@section('content')
    <div id="content">
        <h1>XML Sitemap</h1><p class="expl">
            Generated by <a href="https://yoast.com/">Yoast</a><a href="https://yoast.com/wordpress/plugins/seo/">SEO</a>, this is an XML Sitemap, meant for consumption by search engines.<br>
            You can find more information about XML sitemaps on <a href="http://sitemaps.org">sitemaps.org</a>.
        </p>
        <p class="expl">
            This XML Sitemap Index file contains {{count($maps)}} sitemaps.
        </p>
        <table id="sitemap" cellpadding="3">
            <thead>
            <tr>
                <th class="header" width="75%">Sitemap</th>
                <th class="header" width="25%">Last Modified</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($maps as $k => $map)
            <tr class="{{($k & 1) ? 'odd' : 'even'}}">
                <td>
                    <a href="{{url($map['url'])}}">{{url($map['url'])}}</a>
                </td>
                <td>{{$map['time']}}</td>
            </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection
